pipeline {
    agent any

    environment {
        NODEJS_HOME = tool name: 'NodeJS', type: 'jenkins.plugins.nodejs.tools.NodeJSInstallation'
        PATH = "${env.NODEJS_HOME}/bin:${env.PATH}"
        CHROME_BIN = '/usr/bin/google-chrome'
        DOCKER_HUB_REGISTRY = 'docker.io'
        DOCKERHUB_CREDENTIALS = credentials('dockerhub-credentials')  // Assurez-vous que l'ID des identifiants est correct
       
    }

    stages {
        stage('Checkout') {
            steps {
                script {
                    def repoUrl = 'https://github.com/najwa2222/crda/api-gateway.git'
                    try {
                        echo "Clonage du dépôt depuis ${repoUrl}"
                        git url: repoUrl, credentialsId: 'git-credentials-id'  // Utilise les identifiants Git
                    } catch (e) {
                        error "Échec du clonage du dépôt : ${repoUrl}"
                    }
                }
            }
        }

        stage('Install dependencies') {
            steps {
                script {
                    bat 'npm install'
                    bat 'npm install node-pre-gyp'
                }
            }
        }

        stage('Build') {
            steps {
                bat 'npm run build'
            }
        }

        stage('SonarQube Analysis') {
            steps {
                script {
                    withSonarQubeEnv('SonarQube Test') {  // Assurez-vous que le nom correspond à votre configuration SonarQube
                        bat 'npm run sonarqube'
                    }
                }
            }
        }

        stage('Build API Gateway') {
            steps {
                script {
                    try {
                        echo "Construction de l'image Docker pour API Gateway"
                        dockerImage = docker.build("najwakarrouchi968/api-gateway:latest")
                    } catch (e) {
                        error "Échec de la construction de l'image Docker pour API Gateway"
                    }
                }
            }
        }

        stage('Push API Gateway Image') {
            steps {
                script {
                    try {
                        echo "Poussée de l'image Docker vers DockerHub"
                        docker.withRegistry('https://registry.hub.docker.com', 'dockerhub-credentials') {
                            docker.image('najwakarrouchi968/api-gateway:latest').push()
                        }
                    } catch (e) {
                        error "Échec de la poussée de l'image Docker vers DockerHub"
                    }
                }
            }
        }

        stage('Deploy API Gateway') {
            steps {
                script {
                    withCredentials([file(credentialsId: 'kubeconfig-credentials', variable: 'KUBECONFIG')]) {
                        try {
                            echo "Déploiement de l'API Gateway sur Kubernetes"
                            sh 'kubectl apply -f kubernetes/deployment-api-gateway.yaml'
                        } catch (e) {
                            error "Échec du déploiement de l'API Gateway sur Kubernetes"
                        }
                    }
                }
            }
        }
    }
}
