pipeline {
    agent any

    environment {
        DOCKER_PATH = 'C:\\Program Files\\Docker\\cli-plugins'
        PATH = "${DOCKER_PATH};${PATH}"
        KUBERNETES_NAMESPACE = 'gestiondocuments'
        KUBERNETES_DEPLOYMENT = 'backend'
        DOCKER_IMAGE = 'najwakarrouchi/gestiondocuments'
        DOCKER_TAG = 'latest'
        KUBECONFIG = 'C:\\Users\\acer\\.kube\\config'
        DOCKERFILE_PATH = 'C:\\ProgramData\\Jenkins\\.jenkins\\workspace\\gestiondocuments\\Dockerfile'
    }

    stages {
        stage('Set Up Environment') {
            steps {
                script {
                    echo "Configuration de l'environnement..."
                    bat "echo 'Configuration du chemin Docker : ${DOCKER_PATH}'"
                    bat "echo 'Configuration de KUBECONFIG : ${KUBECONFIG}'"
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    echo "Construction de l'image Docker..."
                    bat "docker build -t ${DOCKER_IMAGE}:${DOCKER_TAG} -f ${DOCKERFILE_PATH} ."
                }
            }
        }

        stage('Verify Docker Image') {
            steps {
                script {
                    echo "Vérification et récupération de l'image Docker..."
                    bat """
                    docker pull ${DOCKER_IMAGE}:${DOCKER_TAG}
                    docker images ${DOCKER_IMAGE}:${DOCKER_TAG}
                    """
                }
            }
        }

        stage('Deploy with kubectl') {
            steps {
                script {
                    bat '''
                    kubectl config view
                    kubectl config use-context docker-desktop
                    kubectl cluster-info
                    kubectl get nodes
                    kubectl get namespace ${gestiondocuments} || kubectl create namespace ${gestiondocuments}
                    kubectl apply -f docker/configMap.yml -n ${gestiondocuments}
                    kubectl apply -f docker/mysqldep.yml -n ${gestiondocuments}
                    kubectl apply -f docker/persistent.yaml -n ${gestiondocuments}
                    kubectl apply -f deployment.yaml -n ${gestiondocuments}
                    '''
                }
            }
        }
    }

    post {
        always {
            echo "Pipeline terminée"
        }
    }
}
