pipeline {
    agent any

    environment {
        DOCKER_PATH = 'C:\\Program Files\\Docker\\cli-plugins'
        PATH = "${DOCKER_PATH};${PATH}"
        KUBERNETES_NAMESPACE = 'scheduling'  // Change this to your desired namespace
        KUBERNETES_DEPLOYMENT = 'backend'
        DOCKER_IMAGE = 'najwakarrouchi/gestiondocuments'
        DOCKER_TAG = 'latest'
        KUBECONFIG = 'C:\\Users\\acer\\.kube\\config'  // Update this path to your actual kubeconfig path
        DOCKERFILE_PATH = 'GestionDocuments/Dockerfile'  // Correct path to your Dockerfile
    }

    stages {
        stage('Set Up Environment') {
            steps {
                script {
                    // Ensure paths and tools are accessible
                    echo "Setting up environment..."
                    bat "echo 'Setting up Docker path: ${DOCKER_PATH}'"
                    bat "echo 'Setting up KUBECONFIG: ${KUBECONFIG}'"
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    // Build and tag the Docker image
                    echo "Building Docker image..."
                    bat "docker build -t ${DOCKER_IMAGE}:${DOCKER_TAG} -f ${DOCKERFILE_PATH} ."
                }
            }
        }

        stage('Verify Docker Image') {
            steps {
                script {
                    // Verify the Docker image exists
                    echo "Verifying and pulling Docker image..."
                    bat """
                    docker pull ${DOCKER_IMAGE}:${DOCKER_TAG}
                    docker images ${DOCKER_IMAGE}:${DOCKER_TAG}
                    """
                }
            }
        }

        stage('Deploy with kubectl') {
            steps {
                script {
                    bat '''
                    kubectl config view
                    kubectl config use-context docker-desktop
                    kubectl cluster-info
                    kubectl get nodes
                    kubectl get namespace ${KUBERNETES_NAMESPACE} || kubectl create namespace ${KUBERNETES_NAMESPACE}
                    kubectl apply -f docker/configMap.yml -n ${KUBERNETES_NAMESPACE}
                    kubectl apply -f docker/mysqldep.yml -n ${KUBERNETES_NAMESPACE}
                    kubectl apply -f docker/persistent.yaml -n ${KUBERNETES_NAMESPACE}
                    kubectl apply -f deployment.yaml -n ${KUBERNETES_NAMESPACE}
                    '''
                }
            }
        }
    }

    post {
        always {
            // Cleanup or additional actions after the pipeline runs
            echo "Pipeline completed"
        }
    }
}
