pipeline {
    agent any

    environment {
        DOCKER_PATH = 'C:\\Program Files\\Docker\\cli-plugins'
        PATH = "${DOCKER_PATH};${env.PATH}"
        KUBECONFIG = 'C:\\Users\\acer\\.kube\\config'
        DOCKERFILE_PATH = 'Dockerfile'
        DOCKER_IMAGE = 'najwakarrouchi/gestiondocuments'
        DOCKER_TAG = 'latest'
    }

    stages {
        stage('Set Up Environment') {
            steps {
                echo 'Setting up environment...'
                script {
                    bat "echo KUBECONFIG Path: ${KUBECONFIG}"
                    bat "echo Configuration du chemin Docker : ${DOCKERFILE_PATH}"
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    echo "Building Docker image..."
                    bat "docker build -t ${DOCKER_IMAGE}:${DOCKER_TAG} -f ${DOCKERFILE_PATH.replace('\\', '/')} ."
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    echo "Pushing Docker image..."
                    withCredentials([usernamePassword(credentialsId: 'docker-hub-credentials', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD')]) {
                        bat """
                        docker login -u %DOCKER_USERNAME% -p %DOCKER_PASSWORD%
                        docker push ${DOCKER_IMAGE}:${DOCKER_TAG}
                        """
                    }
                }
            }
        }

        stage('Verify Docker Image') {
            steps {
                script {
                    echo "Verifying and pulling Docker image..."
                    bat """
                    docker pull ${DOCKER_IMAGE}:${DOCKER_TAG}
                    docker images ${DOCKER_IMAGE}:${DOCKER_TAG}
                    """
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                script {
                    def yamlFile = "deployment-gestiondocument.yaml"
                    
                    bat "kubectl apply -f ${yamlFile} -n gestiondocuments --kubeconfig ${KUBECONFIG}"
                }
            }
        }
    }

    post {
        success {
            echo 'Deployment succeeded!'
        }
        failure {
            echo 'Deployment failed!'
        }
    }
 }
}
