global:
  scrape_interval:     15s # Indique à Prometheus la fréquence à laquelle récupérer les métriques.
  evaluation_interval: 15s # Contrôle la fréquence à laquelle Prometheus évalue les règles d'alerte.


scrape_configs:
  - job_name: 'nodejs_app'
    static_configs:
      - targets:  ['172.16.210.29:9091']
      - labels:
          service: 'my-service'
          group: 'production'
rule_files:
  - 'alert.rules'