pipeline {
    agent any

    environment {
        DOCKERHUB_CREDENTIALS = credentials('dockerhub-credentials')
      
    }

    stages {
        stage('Checkout') {
            steps {
                script {
                    def repoUrl = 'https://github.com/najwa2222/crda/notification.git'
                    try {
                        echo "Clonage du dépôt depuis ${repoUrl}"
                        git url: repoUrl
                    } catch (e) {
                        error "Échec du clonage du dépôt : ${repoUrl}"
                    }
                }
            }
        }

        stage('Build Notification Service') {
            steps {
                script {
                    try {
                        echo "Construction de l'image Docker pour le service Notification"
                        dockerImage = docker.build("najwakarrouchi968/notification:latest")
                    } catch (e) {
                        error "Échec de la construction de l'image Docker pour le service Notification"
                    }
                }
            }
        }

        stage('Test Notification Service') {
            steps {
                script {
                    dockerImage.inside {
                        try {
                            sh 'npm install'
                            sh 'npm test'
                        } catch (e) {
                            error "Échec des tests pour le service Notification"
                        }
                    }
                }
            }
        }

        stage('Push Notification Image') {
            steps {
                script {
                    try {
                        echo "Poussée de l'image Docker vers DockerHub"
                        docker.withRegistry('https://registry.hub.docker.com', 'dockerhub-credentials') {
                            docker.image('najwakarrouchi968/notification:latest').push()
                        }
                    } catch (e) {
                        error "Échec de la poussée de l'image Docker vers DockerHub"
                    }
                }
            }
        }

        stage('Deploy Notification Service') {
            steps {
                script {
                    withCredentials([file(credentialsId: 'kubeconfig-credentials', variable: 'KUBECONFIG')]) {
                        try {
                            echo "Déploiement du service Notification sur Kubernetes"
                            sh 'kubectl apply -f kubernetes/deployment-notification.yaml'
                        } catch (e) {
                            error "Échec du déploiement du service Notification sur Kubernetes"
                        }
                    }
                }
            }
        }
    }
}
