version: '3.8'

services:
  authentification:
    build: ./authentification
    ports:
      - "3001:3001"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=yourpassword
      - DB_NAME=auth

  gestiondocuments:
    build: ./gestiondocuments
    ports:
      - "3004:3004"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=yourpassword
      - DB_NAME=documents

  recherche:
    build: ./recherche
    ports:
      - "3005:3005"
    environment:
      - ELASTICSEARCH_URI=http://elasticsearch:9201

  enregistrement:
    build: ./enregistrement
    ports:
      - "3002:3002"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=yourpassword
      - DB_NAME=collaboration

  notification:
    build: ./notification
    ports:
      - "3003:3003"
    environment:
      - RABBITMQ_URI=amqp://rabbitmq:5672

  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=yourpassword
    volumes:
      - mysql-data:/var/lib/mysql

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    environment:
      - discovery.type=single-node
    ports:
      - "9201:9200"
    volumes:
      - es-data:/usr/share/elasticsearch/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  prometheus:
    image: prom/prometheus
    ports:
      - "9093:9090"
    volumes:
      # Ensure the prometheus.yml file exists at this path on the host
      - C:/ProgramData/Jenkins/.jenkins/workspace/authentification/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - "3008:3000"  # Changed port to 3008 to avoid conflict
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  mysql-data:
  es-data:
  rabbitmq-data:
  grafana-data:
