global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'my_application'
    static_configs:
      - targets: ['localhost:9090'] # Remplacez localhost:9090 par l'adresse et le port de votre application
